### PR TITLE
Upgrade Javet, node, V8, tsc and node-gradle

### PR DESCRIPTION
**Pull request by ammachado**
## What's changed?

Javet, node, V8 tsc and node-gradle have been updated

## What's your motivation?

Running mod on Apache Camel was taking almost 1h. By observation on the progress bar, parsing of javascript files was slow, so I'm updating this project to test later

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've added the license header to any new files through `./gradlew licenseFormat`
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks for putting in the effort in here @ammachado ; had indeed noticed that parsing web resources takes a while on various projects, hope this helps speed that up. I'm not the best judge of the changes here, so I'm hoping @traceyyoshima is able to have a look.

**Comment by ammachado** [comment]
@timtebeek @traceyyoshima I added a test to reproduce the slowness.

**Comment by knutwannheden** [comment]
@ammachado Thanks for your work and your performance test. As you may have noticed this is still work in progress and not all syntactic constructs are supported yet. I did however commit some improvements now which should improve performance and also adds support for some constructs (e.g. the `delete` expression), which weren't supported before.

**Review by traceyyoshima — APPROVED** [review]
Hi @ammachado, Thank you for the PR, and my apologies for taking so long to review the changes! Changes look good -- we'll make a few updates on our end so the build will pass. There was an API change, and a test fails due to an existing parsing issue unrelated to the PR>

**Comment by ammachado** [comment]
@traceyyoshima I'm happy to help.

**Pull request merged**
